### ISSUE TITLE
Error while cloning repository.

### ISSUE THREAD

**Issue by cristianst85** [dlech/KeePassPluginDevTools#1]
When I try to clone your repository I get this error.

"C:\Program Files (x86)\Git\bin\git.exe" clone -v --recurse-submodules --progress --branch master "https://github.com/dlech/KeePassPluginDevTools.git" "D:/Repositories/KeePassPluginDevTools"
Cloning into 'D:/Repositories/KeePassPluginDevTools'...
POST git-upload-pack (300 bytes)
remote: Total 510 (delta 0), reused 0 (delta 0), pack-reused 510  
Checking connectivity... done.
Submodule 'KeePass2.x' (git://github.com/dlech/KeePass2.x) registered for path 'KeePass2.x'
Cloning into 'KeePass2.x'...
fatal: reference is not a tree: c3a45db67c83fe736312893b3d13904fbbbea2c3
Unable to checkout 'c3a45db67c83fe736312893b3d13904fbbbea2c3' in submodule path 'KeePass2.x'
Done

---

GitExtensions 2.48.05
Git 2.5.2.2

**Comment by dlech** [comment]
That's odd. That commit does exist on GitHub. Try manually checkout the VS2015 branch in KeePass2.x instead.

**Comment by cristianst85** [comment]
VS2015 branch in KeePass2.x sub-module is up to-date. The problem appears to be in master branch (superproject).

I get the same error when I try to 'Update all submodules':

"C:\Program Files (x86)\Git\bin\git.exe" submodule update --init --recursive
fatal: reference is not a tree: c3a45db67c83fe736312893b3d13904fbbbea2c3
Unable to checkout 'c3a45db67c83fe736312893b3d13904fbbbea2c3' in submodule path 'KeePass2.x'
Done

![keepassplugindevtools-error](https://cloud.githubusercontent.com/assets/12585988/13229642/af77b17a-d9aa-11e5-880c-7cc042f5336f.png)

---

Also I've updated Git to latest version (2.7.1.2).

**Comment by dlech** [comment]
I just pushed a new commit that updates the submodule. It should work now.

**Comment by cristianst85** [comment]
It works, thank you!
