### ISSUE TITLE
Run-time error with new plugin .plgx

### ISSUE THREAD

**Issue by antboy** [dlech/KeePassPluginDevTools#4]
Hi David, I've made some progress with your helpful .csproj info you sent me by email.  Now the .plgx builds but I get a run-time error when Keepass starts up.  See attached .png screenshot of the error received.
I've also attached the build log and the .csproj file.

To recap, I'm building a Keepass plugin (with Visual Studio 2015 & C#) in one project which needs a .DLL in another adjacent project, hence using your tool.
The plugin works fine when using the 2 .DLLs in the Keepass plugin directory, it's the .plgx I have the problem with.

![plgx_err](https://cloud.githubusercontent.com/assets/254643/22398948/f2fc7c5a-e589-11e6-9d92-da275c5daaf3.png)
[build-log.txt](https://github.com/dlech/KeePassPluginDevTools/files/737070/build-log.txt)
[CardFileKPlugin.csproj.txt](https://github.com/dlech/KeePassPluginDevTools/files/737071/CardFileKPlugin.csproj.txt)

**Comment by dlech** [comment]
Try running `KeePass.exe --debug` with the plgx version. This should save some more detailed information about why the plgx version is not working.

**Comment by dlech** [comment]
I have a hunch that it will say that it cannot find `CardFileRdr.dll`. Did you add a `<PlgxReference>` line to the `<ProjectReference>` like this?

```
<ProjectReference Include="..\SshAgentLib\Ui\WinForms\SshAgentLib.Ui.WinForms.csproj">
      <Project>{3BEB6FAE-B14D-4281-8168-DB2A4A0C5FC4}</Project>
      <Name>SshAgentLib.Ui.WinForms</Name>
      <PlgxReference>..\SshAgentLib\Ui\WinForms\bin\Release\SshAgentLib.WinForms.dll</PlgxReference>
</ProjectReference>
```

**Comment by antboy** [comment]
It turned out to be a redundant inclusion of System.Net.Http which lead to System.Net.Http.dll being undefined at run-time.  I wasn't sure how that got there, so re-built the projects from scratch.  I think it was a Microsoft template that included more by default than was necessary.

Thanks for your help.
